#!/usr/bin/env bash
set -uo pipefail

if ! sls deploy list functions -f preflight -s $STAGE --infrastructure $INFRASTRUCTURE; then
  echo "Preflight is not available, so we cannot replace the function. Skipping..."
else
  sls deploy function -f preflight -s $STAGE --infrastructure $INFRASTRUCTURE
fi
# DO NOT ADD ANYTHING TO THIS SCRIPT
